######################################################################
# Automatically generated by qmake (2.01a) Tue Apr 29 00:41:04 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += scoreboard.h
FORMS += scoreboard.ui
SOURCES += main.cpp scoreboard.cpp
