######################################################################
# Automatically generated by qmake (2.01a) Mon Apr 28 22:45:27 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += scoreboard.h
FORMS += scoreboard.ui
SOURCES += main.cpp scoreboard.cpp
