######################################################################
# Automatically generated by qmake (2.01a) Mon Apr 28 13:56:40 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += gamepad.h
FORMS += gamepad.ui
SOURCES += gamepad.cpp main.cpp
